name: backend CI/CD
on:
  push:
    paths:
      - 'packages/backend/**'
      - '.github/workflows/backend-ci.yaml'
    branches:
      - main

env:
  TARGET_DIR: /www/node-server

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: ssh scp ssh pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      env:
        WELCOME: 'ssh scp ssh pipelines'
      with:
        host: ${{ secrets.DC_HOST }}
        user: ${{ secrets.DC_USER }}
        pass: ${{ secrets.DC_PASS }}
        port: ${{ secrets.DC_PORT }}
        connect_timeout: 10s
        first_ssh: |-
          cp $TARGET_DIR/keys /etc/ 
          rm -rf $TARGET_DIR/ 
          ls -la
          mkdir -p $TARGET_DIR/
          cp /etc/keys $TARGET_DIR/
        scp: |-
          ./packages/backend/* => $TARGET_DIR/
        last_ssh: |-
          npm install -g pnpm
          cd $TARGET_DIR/
          touch .env
          echo  "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> .env
          echo  "SMTP_USER=${{ secrets.SMTP_USER }}" >> .env
          echo  "SMTP_PASS=${{ secrets.SMTP_PASS }}" >> .env
          echo  "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo  "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
          echo  "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env
          npx pnpm install 
          npx pnpm run pullDb 
          npx pnpm run deploy