name: backend CI/CD
on:
  push:
    paths:
      - 'packages/backend/**'
      - '.github/workflows/backend-ci.yaml'
    branches:
      - main

env:
  TARGET_DIR: /www/node-server

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: ssh scp ssh pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      env:
        WELCOME: 'ssh scp ssh pipelines'
        LASTSSH: 'Doing something after copying'
      with:
        host: ${{ secrets.DC_HOST }}
        user: ${{ secrets.DC_USER }}
        pass: ${{ secrets.DC_PASS }}
        port: ${{ secrets.DC_PORT }}
        connect_timeout: 10s
        first_ssh: |-
          rm -rf $TARGET_DIR/
          ls -la
          mkdir -p $TARGET_DIR/
        scp: |-
          ./packages/backend/* => $TARGET_DIR/
      
    - name: start serve
      uses: pnpm/action-setup@0609f0983b7a228f052f81ef4c3d6510cae254ad
      with:
        version: 6.10.0
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
    - run: pnpm install && pnpm run pullDb && pnpm run start
